{{- if .Values.installArgoCD -}}
apiVersion: v1
data:
  server.content.security.policy: default-src * 'unsafe-inline'
  server.x.frame.options: ' '
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
{{- end }}
