####################################################
# installArgoCD enable true will install argo-cd,argo-rollouts,argo-workflows,argo-events,argocd-image-updater
installArgoCD: false

# installArgoRollouts enable true will install argo-rollouts
installArgoRollouts: true
###########################################################################################
#  OEA-AP Install OEA and Argo Services . Change to None if only Argo Services to be installed.
installationMode: None

######################
global:
  # when this flag is set to false; UI will be accessible over http instead of https
  ssl:
    enabled: true

  # Else, the TLS secrets will need to created manually
  certManager:
    installed: true

  createIngress: true

  minio:
    enabled: false

  argorollouts:
    host: "rollouts.ryzon7-argo22.opsmx.org"

  ###############################################################################
  # Set it to false if own LDAP is to be configured
  installOpenLdap: false

  ## ldap configuration used for authentication and authorization
  ldap:
    enabled: false

###################################################
# argo-rollouts configuration
#######################

argo-rollouts:
  # Default set to true . Set to false if crds already exists in the cluster instead of deleting the CRDs
  installCRDs: true
  #Set to false if crds to be deleted as part of helm uninstall
  keepCRDs: false
#######################################################################################################################
# Values of OEA Database
db:
  enabled: false
###############################################################################################################################
forwarder:
  enabled: false
################################################################################################
## Redis configuration
## Set it to false only if OES needs to be configured with external redis
installRedis: false
##########################################################################
