{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: carina
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.carina.serviceAnnotations }}
  annotations:
{{ toYaml .Values.carina.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-carina
spec:
  ports:
  - name: carina
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: oes
    component: carina
  sessionAffinity: None
  type: ClusterIP
{{- end }}
