{{- if and (eq .Values.installationMode "OEA-AP") (.Values.installArgoCD) -}}
{{- if or .Values.autoconfigurecarina .Values.autoconfigureagent -}}
{{- if .Release.IsInstall -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: oes-autoconfigure
  labels:
{{ include "oes.standard-labels" . | indent 4 }}
data:
  datasource-api.sh: |-
    #!/bin/bash
    #set -x
    echo \"Waiting for all Argo Server  to come-up\"
    wait_period=0
    while true
    do
    {{- if and (.Values.global.createIngress) (.Values.global.certManager.installed) }}
    status="$(curl -Is https://{{ .Values.global.argocd.host }} | head -1)"
    validate=$(echo $status | awk '{print $2}')
    {{- else }}
    {{- if and (.Values.global.createIngress) (not .Values.global.certManager.installed) }}
    status="$(curl -Is http://{{ .Values.global.argocd.host }} | head -1)"
    validate=$(echo $status | awk '{print $2}')
    {{- else }}
    validate=$(echo "200")
    {{- end }}
    {{- end }}
    kubectl get po -n {{ .Release.Namespace }} -o jsonpath='{range .items[*]}{..metadata.name}{"\t"}{..containerStatuses..ready}{"\n"}{end}' > /tmp/live.status
    ARGOCDSERVER=$(grep argocd-server /tmp/live.status |grep -v deck | awk '{print $2}')
    OESSAPOR=$(grep oes-sapor /tmp/live.status | awk '{print $2}')
    OESGATE=$(grep oes-gate /tmp/live.status | awk '{print $2}')
    OESUI=$(grep oes-ui /tmp/live.status | awk '{print $2}')
    wait_period=$(($wait_period+10))
    if  [ "$OESUI" == "true" ] && [ "$OESGATE" == "true" ] && [ "$ARGOCDSERVER" == "true" ] && [ "$validate" == "200" ] && [ "$OESSAPOR" == "true" ];
    then
      echo \"ArgocdServer is  Up and Ready..\"
      while true
      do
      ## install argoCLI
      curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      chmod +x /usr/local/bin/argocd
      ## get the user password
      argopassword=$(kubectl get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d)

      ##argocli login
      {{- if and (.Values.global.createIngress) (.Values.global.certManager.installed) }}
      argocd login {{ .Values.global.argocd.host }} --username=admin --password=$argopassword --grpc-web
      {{- else }}
      {{- if and (.Values.global.createIngress) (not .Values.global.certManager.installed) }}
      argocd login {{ .Values.global.argocd.host }} --username=admin --password=$argopassword --grpc-web --insecure
      {{- else }}
      argocd login --insecure --port-forward --port-forward-namespace=opsmx-argo --plaintext --username=admin --password=$argopassword
      {{- end }}
      {{- end }}

      {{- if and (.Values.global.createIngress) (.Values.global.certManager.installed) }}
      token=$(argocd account generate-token)
      {{- else }}
      {{- if and (.Values.global.createIngress) (not .Values.global.certManager.installed) }}
      token=$(argocd account generate-token --insecure)
      {{- else }}
      token=$(argocd account generate-token --insecure --port-forward --port-forward-namespace=opsmx-argo)
      {{- end }}
      {{- end }}
      wait=0
      if [ -z $token ]
      then
        wait=$(($wait+10))
        if [ $wait -gt 2000 ];
        then
          echo \"Script is timed out Admin Secret not found .......\"
          break
        else
          echo \"Waiting to get the admin token\"
          sleep 1m
        fi

      else
         encodedtoken=$(echo -n $token | base64 -w0)
         {{- if .Values.autoconfigurecarina }}
         ## autoconfiguration for carina with isd
         ## replace the secret
         kubectl get secret oes-carina-config -o jsonpath='{.data.*}' | base64 -d > carina-secret.yaml
         yq e '.argos.[].token = "'$encodedtoken'"' carina-secret.yaml > carina-manager.yaml
         kubectl delete secret oes-carina-config
         kubectl create secret generic oes-carina-config  --from-file=carina-manager.yaml
         kubectl delete  po -l component=carina
         break
         {{- end }}
         {{- if .Values.autoconfigureagent }}
         ##create sample SPLUNK integraton
       curl --location --request POST 'http://oes-platform:8095/platformservice/v6/datasource' \
       --header 'Content-Type: application/json' \
       --data-raw '{"datasourceType":"SPLUNK","name":"sample-splunk","configurationFields":{"end_point":"http://demosplunk.in","user_name":"","password":"","dashboard_endpoint":""}}'
         sleep 10
         ## create LOG anf METRIC template
       curl --location --header "x-spinnaker-user:admin"  --request POST 'http://oes-autopilot:8090/autopilot/api/v5/global/metricTemplate' \
       --header 'Content-Type: application/json' \
       --data-raw '{"templateName":"sample-logtemplate","monitoringProvider":"SPLUNK","scoringAlgorithm":"Canary","accountName":"sample-splunk","index":"app*","namespace":null,"regExFilter":false,"regExResponseKey":"","regularExpression":"","filterKey":"kubernetes.container_name","autoBaseline":false,"sensitivity":"high","tags":[],"errorTopics":[{"string":"OnOutOfMemoryError","topic":"CRITICAL","type":"default"},{"string":"StackOverflowError","topic":"CRITICAL","type":"default"},{"string":"ClassNotFoundException","topic":"CRITICAL","type":"default"},{"string":"FileNotFoundException","topic":"CRITICAL","type":"default"},{"string":"ArrayIndexOutOfBounds","topic":"CRITICAL","type":"default"},{"string":"NullPointerException","topic":"CRITICAL","type":"default"},{"string":"StringIndexOutOfBoundsException","topic":"CRITICAL","type":"default"},{"string":"FATAL","topic":"CRITICAL","type":"default"},{"string":"SEVERE","topic":"CRITICAL","type":"default"},{"string":"NoClassDefFoundError","topic":"ERROR","type":"default"},{"string":"NoSuchMethodFoundError","topic":"ERROR","type":"default"},{"string":"NumberFormatException","topic":"ERROR","type":"default"},{"string":"IllegalArgumentException","topic":"ERROR","type":"default"},{"string":"ParseException","topic":"ERROR","type":"default"},{"string":"SQLException","topic":"ERROR","type":"default"},{"string":"ArithmeticException","topic":"ERROR","type":"default"},{"string":"status=404","topic":"ERROR","type":"default"},{"string":"status=500","topic":"ERROR","type":"default"},{"string":"EXCEPTION","topic":"ERROR","type":"default"},{"string":"ERROR","topic":"ERROR","type":"default"},{"string":"WARN","topic":"WARN","type":"default"},{"string":"WARNING","topic":"WARN","type":"default"}],"responseKeywords":"log","logGroupName":"","logStreamName":"","region":"","verificationType":"VERIFICATION","testCaseKey":"","testSuiteKey":"","infoScoring":false,"contextualCluster":false,"contextualWindowSize":25,"tagEnabled":false,"streamId":"","timestampKey":"","applicationId":0,"applicationName":"","emailId":""}' > /dev/null


       curl --location --request POST 'http://oes-autopilot:8090/autopilot/api/v5/global/metricTemplate' \
       --header "x-spinnaker-user:admin" \
       --header 'Content-Type: application/json' \
       --data-raw '{"isEdit":false,"templateName":"sample-metrictemplate2","data":{"groups":[],"isNormalize":false,"percent_diff_threshold":"hard"},"filterKey":"container_Id"}' > /dev/null


         ##Configure the Agent to the ISD
         #Create Agent in the ISD-UI via API
         sleep 20
         curl --location --request POST 'http://oes-sapor:8085/oes/accountsConfig/v3/agents?cdType=Argo' --header 'Content-Type: application/json' --header 'x-spinnaker-user: admin'  --data-raw '{"agentName":"isd-argo-agent","description":"default isd-argo"}'
         sleep 20
         ## Download agent manifest file
         curl --location --request GET 'http://oes-sapor:8085/oes/accountsConfig/agents/isd-argo-agent/manifest' --header 'x-spinnaker-user: admin' > /tmp/manifest.yaml
         cd /tmp/
         ## Download and install the kubectl-slice to split to manifest file that is download
         wget https://github.com/patrickdappollonio/kubectl-slice/releases/download/v1.2.3/kubectl-slice_1.2.3_linux_x86_64.tar.gz
         tar -xvf /tmp/kubectl-slice_1.2.3_linux_x86_64.tar.gz
         cp /tmp/kubectl-slice /usr/local/bin/
         ## create a directory to place splited yamls from the manifest
         mkdir /tmp/yamls
         kubectl-slice --input-file=/tmp/manifest.yaml --output-dir=/tmp/yamls/.
         ## Replace the namespace in the manifest
         yq e -i '.subjects[0].namespace = "{{ .Release.Namespace }}"' /tmp/yamls/clusterrolebinding-opsmx-agent-isd-argo-agent.yaml
         ## Adding the agent service configmap with added arocd token
         kubectl get cm opsmx-services-isd-argo-agent -o yaml > /tmp/agent-cm.yaml
         sed -i 's/token: .*xxx/token: '$encodedtoken'/g' /tmp/agent-cm.yaml
         ## Apply the yamls
         kubectl replace --force -f /tmp/agent-cm.yaml
         kubectl apply -f /tmp/yamls/
         break
         {{- end }}
      fi
      done
      break
    else
      if [ $wait_period -gt 2000 ];
      then
       echo \"Script is timed out as the Argocd Server is not ready yet.......\"
       break
      else
       echo \"Waiting for  Argocd Server to be ready\"
       sleep 30
      fi
    fi
    done
{{- end -}}
{{- end -}}
{{- end -}}
