{{- if (eq .Values.installationMode "OEA-AP") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: ui
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.ui.serviceAnnotations }}
  annotations:
{{ toYaml .Values.ui.serviceAnnotations | indent 4 }}
{{- end }}
  name: oes-ui
spec:
  type: ClusterIP
  ports:
  - name: "https"
    port: 443
    targetPort: 8080
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: oes
    component: ui
{{- end -}}
